services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: notes-app-backend
    container_name: notes-app-backend
    user: "${UID}:${GID}"
    volumes:
      - ./backend:/var/www/html
    networks:
      - notes-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: notes-app-frontend
    container_name: notes-app-frontend
    user: "${UID}:${GID}"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - notes-network
    command: npm run dev

  webserver:
    image: nginx:alpine
    container_name: notes-app-webserver
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - notes-network

networks:
  notes-network:
    driver: bridge